### PR TITLE
If the project variable 'searchlayers-plugin' is present, only the specified layer is covered.

### PR DESCRIPTION
**Pull request by yamamoto-ryuzo**
It is always convenient for us.
I added this function because there are times when I want to specify a search layer.
Currently, we are using this search function and our own search function.
Now that you have added Japanese-language support, we would like to integrate the functions into this one, if possible.
If you think this is a good feature, please approve it.
For your information, I am not sure about the English in the comments, so please correct it.

### CODE REVIEW

**Comment by yamamoto-ryuzo** [comment]
If I have time, I will also check if <All Layers> and so on can be included in the translation.
We are working on it.
image

**Comment by hamiltoncj** [comment]
I'm not going go forward with this pull request. I updated the other translated fields and they have been added to github. There was one other string that I found that I added the tr() around it so you have another one to translate.

As for the rest of the changes, I don't understand what they are trying to do. What does this add. I need to make sure the changes are good for everyone. Apparently, you also introduced some visual studio files. I don't use visual studio so I don't want them added.

**Comment by hamiltoncj** [comment]
I am going close this, but please explain in more details what this does and why it is useful. If I decide this would be good for the whole community then I will consider accepting a new pull request.

There is one more string that needs translation. Go ahead and translate it and do another pull request just for the translation. I will push out a new release after that. They only file you need to update is searchLayers_ja.ts. My script will generate the .qm file.

**Comment by yamamoto-ryuzo** [comment]
The two operations are interlocked.
Actually, translation is not the main issue, so I will reiterate the main issue and pull it out for clarity.
Thank you .

**Pull request closed without merging**
