### PR TITLE
Update searchLayers_ja.ts

### PR DESCRIPTION
**Pull request by yamamoto-ryuzo**
This is my first time to Pull on GitHUB.
If something is wrong, I will change to email.
Thank you in advance.

### CODE REVIEW

**Comment by hamiltoncj** [comment]
@yamamoto-ryuzo That looks good. I checked it and seems to be working correctly so I released version 3.0.8. If there are any problems please let me know.

**Comment by yamamoto-ryuzo** [comment]
Thank you very much for your prompt response.
We immediately found a translation error, but it is not fatal and we will correct it together.
We are currently requesting confirmation from all Japanese institutions that can present the information.

https://www.facebook.com/groups/lizmapusergroupjapan/permalink/1079100492685348

**Comment by hamiltoncj** [comment]
@yamamoto-ryuzo When ever you are ready with a new translation, just do another pull request with the translation file and I will update the plugin.

**Comment by yamamoto-ryuzo** [comment]
Thank you for your cooperation.
I am currently publishing the translation on Facebook, where I am a 
member, and asking everyone to check the inconsistencies in the translation.
I plan to revise the translation once it is boiled down to a certain level.
Thank you very much for your cooperation.

**Pull request merged**
