### PR TITLE
Update searchLayers_ja.ts

### PR DESCRIPTION
**Pull request by yamamoto-ryuzo**
Correction of translation errors

### CODE REVIEW

**Comment by hamiltoncj** [comment]
@yamamoto-ryuzo Right before you did this I released new Search Layers. I just updated the i18n/searchLayers_ja.qm on github. Replace your local QGIS Search Layers plugin i18n/searchLayers_ja.qm file with this one in github. Make sure the the translation looks correct and let me know. If there are no problems, then I will update it next week in plugins.qgis.org.

**Comment by yamamoto-ryuzo** [comment]
It is working fine.
image

**Comment by hamiltoncj** [comment]
I posted the updated plugin 3.0.10 to plugins.qgis.org.

**Comment by yamamoto-ryuzo** [comment]
I wondered how long the forks would remain.
Thank you very much.

**Pull request merged**
